### ISSUE TITLE
About translation

### ISSUE THREAD

**Issue by ghost** [MidsizeMango/Notes#1]
Could you update this repository please? I would like translate this app in my language.

**Comment by prasadshirvandkar** [comment]
Well..this is just a part of my App "Material Notes" on Play Store Written in Kotlin. My Full App is Written in Java. This Repository was just to show a Demo of Kotlin.

**Comment by ghost** [comment]
Sorry I did not realize it was just a demo.
About my request would be possible to put strings to be translated in this repo or perhaps open a new one?

**Comment by prasadshirvandkar** [comment]
Yeah..Absolutely Possible.
